export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PATIENT = 'GET_PATIENT';
export const PATIENT_LOADING = 'PATIENT_LOADING';
export const PATIENT_NOT_FOUND = 'PATIENT_NOT_FOUND';
export const CLEAR_CURRENT_PATIENT = 'CLEAR_CURRENT_PATIENT';
export const GET_PATIENTS = 'GET_PATIENTS';
